### PR TITLE
Added pylint, coverage, and virtualenv as well as instructions

### PR DESCRIPTION
**Pull request by mac-chaffee**
Thought I'd try to add some good coding practices into the project while it's still new.
You could completely ignore coverage and linting if you want, but it's set up if you're interested!

### CODE REVIEW

**Comment by nagracks** [comment]
Thank you.

We want to make this app pluggable, all stuff you added doesn't make sense to me.

**Comment by mac-chaffee** [comment]
Ah, by "pluggable", do you mean you don't intend for this project to be a full, standalone Django app?

My mistake. I'll remove the settings.py, wsgi.py, manage.py stuff, but I'll leave pylint and coverage (with some added explanations!) tomorrow.

**Comment by nagracks** [comment]
Yes we want to make standlone Django app.

**Comment by nagracks** [comment]
Pylint and coverage are not required for this project. You can use if you want

**Pull request closed without merging**
